name: Automate Milestones and Versioning.

# This workflow ensures that you will always have milestones up.

on:
  push:
    branches:
      - "main"

jobs:
  autopush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      # Ensure versioning files are up-to-date from looking at tags.

      - uses: autosuite/autoversion@master

      # Create milestones based on the current tag version (or 0.1.0 and 1.0.0 for new repos).

      - uses: autosuite/automilestone@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}

      # Commit and push any and all changes.

      - uses: autosuite/autocommit@master
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
