name: Automate Milestones, Versioning, README.MD badges, and CHANGELOG.md.

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12']
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node }}
      - name: Build w/ NPM
        run: |
          npm ci
          npm install
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
  autopush:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      # From the latest valid version tag, ensure README.md and versioning files are up-to-date.

      - uses: autosuite/autobadge@master
      - uses: autosuite/autoversion@master

      # Create milestones based on the current tag version (or 0.1.0 and 1.0.0 for new repos).

      - uses: autosuite/automilestone@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}

      # Automatically write the CHANGELOG.md file based on GitHub Issues, git tags, and Milestones.

      - uses: autosuite/autolog@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}

      # Commit and push any and all changes.

      - uses: autosuite/autocommit@master
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
